services:
  editor:
    build: 
      context: .
      dockerfile: .devcontainer/Dockerfile
    container_name: docusaurus-editor
    userns_mode: "keep-id"
    ports:
      - "8080:8080" # Code-Server (エディタ)
      - "3000:3000" # Docusaurus (プレビュー)
    volumes:
      - .:/app:Z
      - gh-config:/home/node/.config/gh:Z
    environment:
      - PASSWORD=${CODE_SERVER_PASSWORD}
      - GIT_USER_NAME=${GIT_USER_NAME}
      - GIT_USER_EMAIL=${GIT_USER_EMAIL}

volumes:
  gh-config:
