name: "機能リクエスト"
description: ウェブサイトへの機能追加や改善の提案
title: "feature: (概要を簡潔に記述)"
labels: ["enhancement"]
body:
  - type: markdown
    attributes:
      value: |
        ウェブサイトの改善案をご提案いただきありがとうございます．どのような機能が必要か詳細にご説明ください．
        
  - type: input
    id: abstract
    attributes:
      label: "概要"
      description: "どのような機能なのかを簡潔に記述してください"
      placeholder: "簡潔に記述してください"
    validations:
      required: true

  - type: textarea
    id: goal
    attributes:
      label: "目的"
      description: "この機能があるとユーザにどのように役立つか簡潔に記述してください"
      placeholder: "簡潔に記述してください"
    validations:
      required: false

  - type: textarea
    id: solution
    attributes:
      label: "実装案"
      description: "可能であれば，どのような機能やデザインが適切か，具体的な案をご提示ください"
      placeholder: "具体的に記述してください"
    validations:
      required: false
      
  - type: textarea
    id: alternatives
    attributes:
      label: "検討した代替案"
      description: "この機能以外に考えられる代替案や，なぜこの解決策が最適だと考えるか，理由を記述してください"
      placeholder: "具体的に記述してください"
    validations:
      required: false
      
  - type: textarea
    id: additional
    attributes:
      label: "その他，補足情報"
      description: "参考となるURL，デザインのスケッチなどがあればご提供ください"
      placeholder: "簡潔に記述してください"
    validations:
      required: false